---
- name: Download Docker compose from Github
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose.version }}/docker-compose-{{ ansible_system | lower }}-armv7"
    dest: "/usr/local/bin/docker-compose"
    mode: 0775

