# my global config
global:
  scrape_interval:     15s
  evaluation_interval: 15s
  scrape_timeout: 10s
  external_labels:
      monitor: 'isp-monitoring'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
         - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
    - targets: ['node-exporter:9100']


  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets: {{ blackbox.targets }}
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'speedtest'
    metrics_path: /metrics
    scrape_interval: 60m
    scrape_timeout: 60s  # running speedtest needs time to complete

    static_configs:
      - targets: ['speedtest:9798']

  - job_name: 'pihole'
    static_configs:
      - targets: ['pihole-exporter:9617']
